import type { NextPage } from "next";
import Head from "next/head";
import Banner from "../Components/Banner";
import { CardsSlide } from "../Components/CardsSlide";
import Header from "../Components/Header";
import teams from "./teams";
import bird from "../../public/imgs/enactus_bird.png"
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <div className="relative">
      <Head>
        <title>Enactus SMIT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Banner />
      <section className="relative flex bg-gradient-to-r from-yellow-400">
        <div className="flex flex-col ml-8 mt-6 mb-10 lg:flex lg:flex-col lg:ml-20 w-[80%] md:w-[65%] lg:w-[50%] lg:mt-16 lg:mb-24 z-10">
          <h1 className="whitespace-nowrap text-[3rem] md:text-[3.5rem] lg:text-[5.2rem] font-semibold text-gray-900 bg-gradient-to-bl from-purple-500 via-slate-800 to-slate-900
          bg-clip-text text-transparent">Who We Are</h1>
          <p className="text-justify md:text-[1.2rem] lg:text-[1.5rem] text-gray-900 font-medium indent-20 mt-8 leading-relaxed">
            <span className="text-[1.3rem] md:text-[1.7rem] lg:text-[2rem] font-semibold">Enactus </span> 
            is a network of global leaders that use effective business strategies
            for positive social and environmental impact. It is a non-profit organisation
            that uses the United Nations 17 Sustainable Development Goals as a framework
            to bring about a change and create a better world for everyone.
            Enactus SMIT is a newly formed chapter of this global platform. Since our
            establishment in 2022, we&apos;ve been actively working on our first project
            <span className="lg:text-[1.6rem] font-semibold"> अन्न-Drishti</span>. Backed by a strong core team and supportive local businesses,
            we aim to make our surroundings more sustainable than ever.
          </p>
        </div>
        <div className="absolute right-0 mt-20 w-[300px] md:mt-20 md:w-[400px] opacity-40 md:opacity-75 lg:opacity-90 lg:w-[700px] -z-0">
          <Image
            src = {bird}

            alt = "bird"
          />
        </div>
      </section>

    </div>
  );
};

export default Home;
