import Head from "next/head";
import React from "react";

function teams() {
  return (
    <div className="">
      <Head>
        <title>Our teams</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
}

export default teams;
