import Head from "next/head";
import React from "react";

const updates = () => {
  return (
    <div className="">
      <Head>
        <title>Updates</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      updates
    </div>
  );
};

export default updates;
