import Head from 'next/head'
import React from 'react'

const whatWe = () => {
  return (
    <div className="">
      <Head>
        <title>What we do</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      whatWe
    </div>
  )
}

export default whatWe