import Head from 'next/head'
import React from 'react'

const who = () => {
  return (
    <div className="">
      <Head>
        <title>Who we are</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Who we are
    </div>
  )
}

export default who